#ifndef EDA_CORE_H
#define EDA_CORE_H

/* Generated with cbindgen:0.27.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace eda {
#endif  // __cplusplus

// FFI-compatible output destination structure
typedef struct COutputDestination {
  uint32_t dest_type;
  char *target;
  char *cluster;
} COutputDestination;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// FFI-compatible function to get Kafka broker
// Returns a C string that must be freed by the caller
char *eda_get_kafka_broker(void);

// FFI-compatible function to get Kafka topic
// Returns a C string that must be freed by the caller
char *eda_get_kafka_topic(void);

// FFI-compatible function to get Kafka consumer group
// Returns a C string that must be freed by the caller
char *eda_get_kafka_group(void);

// FFI-compatible function to free C strings returned by this library
void eda_free_string(char *s);

uint32_t eda_classify_error(const char *error);

uint64_t eda_get_retry_decision(uint32_t error_category, uint32_t attempt, uint32_t max_attempts);

int32_t eda_should_retry(const char *error, uint32_t attempt);

uint64_t eda_calculate_backoff(uint32_t attempt);

struct COutputDestination *eda_get_output_destination(const char *event_json);

void eda_free_output_destination(struct COutputDestination *dest);

// Load routing configuration from a YAML file via FFI
bool eda_load_routing_config(const char *file_path);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#ifdef __cplusplus
}  // namespace eda
#endif  // __cplusplus

#endif  /* EDA_CORE_H */
